import { CurriculoMultidisciplinar } from "./types";

export const DEFAULT_CURRICULOS: CurriculoMultidisciplinar = {
  activeArea: "Gestão",
  areas: {
    "Gestão": {
      nome: "Joás Kelph",
      fotoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300&h=300",
      tituloProfissional: "Suporte Técnico e Análise de Dados",
      contato: {
        email: "joaskelph18@gmail.com",
        telefone: "(63) 93300-5939",
        localizacao: "Palmas, TO - Brasil",
        linkedin: "linkedin.com/in/joaskelph",
        github: "github.com/Joas-Kelph",
        website: "",
        instagram: "",
      },
      resumo: "Profissional com sólida base técnica em informática e gestão, cursando Engenharia de Software. Possuo qualificações específicas em Gestão Financeira, Gestão de Pessoas e Proteção de Dados (LGPD). Destaco-me pela facilidade com ferramentas digitais, capacidade analítica na elaboração de relatórios e foco na qualidade do atendimento e melhoria de processos internos.",
      experiencias: [
        {
          id: "g1",
          empresa: "SENAI / Lojas Tocantinenses",
          cargo: "Suporte Técnico e Análise de Dados",
          periodo: "2025",
          descricao: "Gestão de bancos de dados e organização de arquivos digitais. Elaboração de dashboards e relatórios para acompanhamento de indicadores. Atendimento e suporte ao usuário, garantindo a agilidade na resolução de problemas. Monitoramento de sistemas e manutenção preventiva de equipamentos.",
        },
        {
          id: "g2",
          empresa: "Grand Prix SENAI (2 edições)",
          cargo: "Experiência e Competidor Técnica",
          periodo: "Grand Prix SENAI (2 edições)",
          descricao: "Resolução de problemas reais: Desenvolvimento de soluções estratégicas para desafios reais de empresas em maratonas de 72 horas. Foco em Resultados: Diagnóstico ágil de gargalos operacionais e proposição de melhorias com foco em eficiência e redução de custos. Soft Skills: Demonstração de alta capacidade de trabalho sob pressão, liderança colaborativa e gestão de tempo crítica.",
        },
      ],
      educacoes: [
        {
          id: "ged1",
          instituicao: "Centro Universitário Luterano de Palmas - CEULP/ULBRA",
          curso: "Graduação em Engenharia de Software",
          periodo: "2025 – 2028 (Previsão)",
          descricao: "Foco em: Arquitetura de Software e Desenvolvimento Full Stack.",
        },
        {
          id: "ged2",
          instituicao: "Senai - Cetec Palmas",
          curso: "Curso Técnico em Informática",
          periodo: "2024 – 2025",
          descricao: "Destaque: Redes de computadores, suporte e lógica de programação.",
        },
      ],
      habilidades: [
        "Gestão Financeira & de Pessoas",
        "Análise e Gestão de Dados",
        "Pacote Office (Excel, Word)",
        "Ferramentas Google",
        "Gestão de Documentação",
        "Proteção de Dados (LGPD)",
        "Comunicação Assertiva",
        "Organização e Gestão de Tempo",
        "Raciocínio Lógico & Proatividade",
        "Trabalho em Equipe",
      ],
      idiomas: [
        { id: "gi1", idioma: "Português", nivel: "Nativo" },
        { id: "gi2", idioma: "Inglês", nivel: "Técnico / Leitura" },
        { id: "gi3", idioma: "Espanhol", nivel: "Básico / Intermediário" },
      ],
      certificacoes: [
        "Gestão Financeira",
        "Gestão de Pessoas",
        "Qualidade no Atendimento ao Cliente",
        "Proteção de Dados na LGPD",
        "E-commerce e Gestão Comercial",
        "Liderança e Promoção da Inovação",
        "Marketing Digital e Storytelling",
        "Introdução à Ciência de Dados e IA Generativa",
      ],
    },
    "Confeitaria": {
      nome: "Joás Kelph",
      fotoUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=300&h=300",
      tituloProfissional: "Chef Confeiteiro Especialista em Patisserie Fina",
      contato: {
        email: "joaskelph18@gmail.com",
        telefone: "(63) 93300-5939",
        localizacao: "Palmas, TO - Brasil",
        linkedin: "linkedin.com/in/joaskelph",
        github: "github.com/Joas-Kelph",
        website: "",
        instagram: "@jottaconfeitaria",
      },
      resumo: "Chef Confeiteiro apaixonado pela arte dos doces, com profunda expertise em confeitaria fina clássica e moderna. Ampla vivência no desenvolvimento de cardápios de sobremesas exclusivas, elaboração de bolos artísticos esculpidos, folhados e tortas finas francesas. Forte domínio de técnicas de chocolataria, controle de custos de receitas e práticas de extrema higiene e segurança de alimentos (sistema HACCP). Autônomo criativo à frente do Jotta Confeitaria.",
      experiencias: [
        {
          id: "c0",
          empresa: "Jotta Confeitaria (@jottaconfeitaria)",
          cargo: "Confeiteiro e Idealizador / Criador de Conteúdo",
          periodo: "2023 - Presente",
          descricao: "Criação, produção artesanal e comercialização de bolos requintados sob encomenda, tortas e sobremesas exclusivas. Divulgação ativa em mídias digitais e produção de conteúdo dinâmico de produção e finalização, cultivando uma comunidade fiel de clientes fiéis.",
        },
        {
          id: "c1",
          empresa: "Patisserie Douce Amour",
          cargo: "Confeiteiro Sênior",
          periodo: "Dezembro de 2022 - Presente",
          descricao: "Responsável direto pela criação de menus de cupcakes, macarons, tortas finas francesas (entremets) e sobremesas sazonais de inverno e verão. Execução impecável de acabamentos refinados (marmorizado, glaçagem espelhada) e esculturas de chocolate artístico. Organização rigorosa de fichas técnicas de porcionamento para garantia de homogeneidade e lucratividade práticos de cada doce.",
        },
        {
          id: "c2",
          empresa: "Boutique de Panificação Trigo Real",
          cargo: "Auxiliar Chef de Confeitaria",
          periodo: "Fevereiro de 2020 - Outubro de 2022",
          descricao: "Preparação prévia de bases de confeitaria clássica (masa sablée, folhada, choux, pão de ló). Elaboração profissional de recheios delicados (creme de confeiteiro, mousses, ganaches especiais, merengues, caldas). Manutenção contínua de rígidos quesitos sanitários de bancadas.",
        },
      ],
      educacoes: [
        {
          id: "ced1",
          instituicao: "Universidade Luterana do Brasil (ULBRA)",
          curso: "Tecnólogo em Gastronomia",
          periodo: "2019 - 2021",
          descricao: "Ênfase em Confeitaria Clássica Europeia, Práticas Profissionais de Panificação, Higiene Sanitária e Nutrição.",
        },
        {
          id: "ced2",
          instituicao: "Instituto Gastronômico das Américas (IGA)",
          curso: "Especialização em Confeitaria Fina e Chocolataria",
          periodo: "2021 - 2022",
        },
      ],
      habilidades: [
        "Patisserie Fina Clássica",
        "Chocolataria & Temperagem",
        "Glaçagem & Coberturas",
        "Fichas Técnicas & Porcionamento",
        "Bolo Artístico Decorado",
        "Controle sanitário (HACCP)",
        "Preparo de Massas de Base",
      ],
      idiomas: [
        { id: "ci1", idioma: "Português", nivel: "Nativo" },
        { id: "ci2", idioma: "Espanhol", nivel: "Básico" },
      ],
      certificacoes: [
        "Confeitaria – IFRS (Instituto Federal do Rio Grande do Sul)",
        "Confeitaria para Iniciantes",
        "Curso de Pasta Americana Básico",
        "Gastronomia: História – Evolução e Cultura",
        "Ruffles Cake com Magnólias de Açúcar",
        "Curso Prático de Higiene e Manipulação Alimentar",
        "Masterclass em Arte em Açúcar e Isomalte de Alto Padrão - Atelier Gastronômico",
      ],
    },
    "Atendimento ao Público": {
      nome: "Joás Kelph",
      fotoUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&q=80&w=300&h=300",
      tituloProfissional: "Supervisor e Atendente de Loja",
      contato: {
        email: "joaskelph@rede.ulbra.br",
        telefone: "(63) 93300-5939",
        localizacao: "Palmas, TO - Brasil",
        linkedin: "linkedin.com/in/joaskelph",
        github: "github.com/Joas-Kelph",
        website: "",
        instagram: "",
      },
      resumo: "Profissional com experiência em atendimento ao cliente, vendas e organização de estoque, atuando em empresas de diferentes segmentos. Possuo facilidade em comunicação, agilidade no atendimento, apoio no processo de vendas, reposição e controle de mercadorias. Sou pontual, dedicado, organizado e sempre disposto a aprender, contribuindo para um ambiente de trabalho produtivo, eficiente e positivo.",
      experiencias: [
        {
          id: "as1",
          empresa: "L’Occitane au Brésil",
          cargo: "Supervisor de Loja",
          periodo: "Janeiro de 2025 – Abril de 2025",
          descricao: "Supervisão e apoio à equipe de vendas, orientando no atendimento ao cliente e cumprimento de metas. Orientação, treinamento e apoio aos colaboradores nas rotinas diárias da loja. Organização das escalas de trabalho e distribuição de tarefas da equipe. Acompanhamento dos indicadores de vendas e apoio em ações para melhoria de resultados. Controle e acompanhamento do estoque, inventários e reposição de mercadorias. Conferência de recebimento de produtos e apoio aos processos logísticos. Suporte à abertura e fechamento da loja, assegurando o cumprimento dos procedimentos internos.",
        },
        {
          id: "as2",
          empresa: "Leitura Palmas",
          cargo: "Atendente / Assistente de Loja",
          periodo: "Novembro de 2022 – Janeiro de 2025",
          descricao: "Auxílio na organização da loja, atendimento presencial e orientação aos clientes sobre produtos. Responsável pelo recebimento, organização e controle de livros e materiais em estoque. Realização de inventários, reposição de mercadorias e conferência de entradas e saídas. Apoio ao processo logístico, garantindo a correta armazenagem, conservação e disponibilidade dos produtos.",
        },
      ],
      educacoes: [
        {
          id: "aed1",
          instituicao: "Centro Universitário Luterano de Palmas - CEULP/ULBRA",
          curso: "Graduação em Engenharia de Software",
          periodo: "2025 – 2028 (Previsão)",
          descricao: "Foco em: Arquitetura de Software e Desenvolvimento Full Stack.",
        },
        {
          id: "aed2",
          instituicao: "Senai - Cetec Palmas",
          curso: "Curso Técnico em Informática",
          periodo: "2024 – 2025",
          descricao: "Destaque: Redes de computadores, suporte e lógica de programação.",
        },
        {
          id: "aed3",
          instituicao: "CEMT - Centro de Ensino Médio de Taquaralto",
          curso: "Ensino Médio Completo",
          periodo: "2022",
          descricao: "",
        },
      ],
      habilidades: [
        "Liderança e Gestão de Equipes",
        "Foco em Resultados e Metas",
        "Tomada de Decisão",
        "Gestão de Estoque e Operação",
        "Comunicação Eficaz",
        "Flexibilidade de Escalas",
        "Rotinas Administrativas e Operacionais",
        "Organização e Gestão de Tempo",
        "Raciocínio Lógico & Proatividade",
        "Trabalho em Equipe",
      ],
      idiomas: [
        { id: "ai1", idioma: "Português", nivel: "Nativo" },
        { id: "ai2", idioma: "Inglês", nivel: "Técnico / Leitura" },
        { id: "ai3", idioma: "Espanhol", nivel: "Básico / Intermediário" },
      ],
      certificacoes: [
        "Grand Prix SENAI de Inovação – Etapa Escolar",
        "Gestão de Pessoas - SEBRAE",
        "Gestão Financeira - SEBRAE",
        "Gestão de Bares e Restaurantes - SEBRAE",
        "Qualidade no Atendimento - SEBRAE",
        "E-commerce e Gestão Comercial - SEBRAE",
        "Proteção de Dados na LGPD - SEBRAE",
      ],
    },
    "Padaria": {
      nome: "Joás Kelph",
      fotoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=300&h=300",
      tituloProfissional: "Padeiro Sênior e Especialista em Fermentação Natural",
      contato: {
        email: "joaskelph18@gmail.com",
        telefone: "(63) 93300-5939",
        localizacao: "Palmas, TO - Brasil",
        linkedin: "linkedin.com/in/joaskelph",
        github: "github.com/Joas-Kelph",
        website: "",
        instagram: "@jottaconfeitaria",
      },
      resumo: "Padeiro Técnico Artesanal especializado no clássico Sourdough (Fermentação Natural Lenta) e panificações internacionais clássicas (Croissants, Brioches, Ciabattas). Experiente em gerenciar volumes pesados de batimento de massas, cilindragem segura, modelagem inteiramente manual, cálculo exato de hidratação (percentual do padeiro) e acompanhamento técnico de forneamento em lastros avançados.",
      experiencias: [
        {
          id: "p1",
          empresa: "Pães Artesanais Miolo & Trigo",
          cargo: "Padeiro Responsável Sênior",
          periodo: "Julho de 2022 - Presente",
          descricao: "Gerenciamento completo das produções de massas rústicas francesas e panetones natalinos do tipo italiano gourmet. Manutenção primorosa de culturas de levedas selvagens (Levain de 5 anos de cuidado). Gestão segura de temperaturas de assamento em fornos de lastro de grande porte e coordenação de dois padeiros juniores.",
        },
        {
          id: "p2",
          empresa: "Panificadora Tradicional Central",
          cargo: "Modelador de Forno e Massas de Pão",
          periodo: "Agosto de 2019 - Junho de 2022",
          descricao: "Preparações em massa de pão de sal clássico colonial brasileiro, massas semidoces, fatias hungaras e enrolados tradicionais. Operação contínua de amassadeiras rápidas, divisoras automáticas e cilindros, respeitando todas as normas rígidas brasileiras de segurança do trabalho em padaria.",
        },
      ],
      educacoes: [
        {
          id: "ped1",
          instituicao: "Senac Porto Alegre",
          curso: "Curso Técnico Profissionalizante em Panificação Comercial",
          periodo: "2018 - 2019",
          descricao: "Enfoque em Engenharia de Panificação Comercial, Processos Biológicos de Leveduras, Métodos de Resfriamento e Segurança Industrial.",
        },
      ],
      habilidades: [
        "Fermentação Lenta (Levain)",
        "Modelagem Artesanal Manual",
        "Percentual do Padeiro (Fórmulas)",
        "Operação Forno de Lastro & Vapor",
        "Controle de Maturação a Frio",
        "Croissants & Folhados Finos",
        "Boas Práticas de Fabricação (BPF)",
      ],
      idiomas: [
        { id: "pi1", idioma: "Português", nivel: "Nativo" },
        { id: "pi2", idioma: "Inglês", nivel: "Básico" },
      ],
      certificacoes: [
        "Salgadeiro Profissional – SENAC",
        "Boas Práticas Sanitárias Industriais de Alimentos - ANVISA",
        "Workshop Avançado de Panetone Artesanal Italiano de Alta Hidratação - Lievito Madre",
      ],
    },
    "Tecnologia da Informação": {
      nome: "Joás Kelph",
      fotoUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&q=80&w=300&h=300",
      tituloProfissional: "Desenvolvedor de Software & Técnico em Informática",
      contato: {
        email: "joaskelph@rede.ulbra.br",
        telefone: "(63) 93300-5939",
        localizacao: "Palmas, TO - Brasil",
        linkedin: "linkedin.com/in/joaskelph",
        github: "github.com/Joas-Kelph",
        website: "",
        instagram: "",
      },
      resumo: "Estudante de Engenharia de Software e Técnico em Informática, com foco em desenvolvimento de sistemas e infraestrutura. Possuo base sólida em desenvolvimento web utilizando Python, JavaScript e Node.js, além de experiência com versionamento de código (Git) e lógica computacional. Tenho facilidade em resolver problemas técnicos complexos e busco constantemente aplicar boas práticas de desenvolvimento e novas tecnologias para criar soluções eficientes e escaláveis.",
      experiencias: [
        {
          id: "it1",
          empresa: "Lojas Tocantinenses",
          cargo: "Desenvolvimento Web - SENAI",
          periodo: "2025",
          descricao: "Desenvolvimento de aplicações web utilizando HTML, CSS, JavaScript e Node.js. Criação de interfaces responsivas e integração com back-end. Aplicação de boas práticas de organização de código, versionamento e design.",
        },
        {
          id: "it2",
          empresa: "Grand Prix SENAI",
          cargo: "Competição Técnica (2 edições)",
          periodo: "Participações",
          descricao: "Conquista de pódio em ambas as participações. Resolução de desafios técnicos em equipe, com foco em eficiência e qualidade. Desenvolvimento de habilidades como pensamento lógico, trabalho sob pressão e colaboração.",
        },
        {
          id: "it3",
          empresa: "SENAI",
          cargo: "Formação Técnica - Módulos Práticos",
          periodo: "2024 - 2025",
          descricao: "Estudo de Lógica de Programação e Estrutura de Computadores. Desenvolvimento de Sistemas e Manipulação de Bancos de Dados. Gestão da Segurança da Informação e boas práticas em TI. Elaboração de dashboards e análise de dados.",
        },
        {
          id: "it4",
          empresa: "SENAI",
          cargo: "Serviços de Manutenção de Microcomputadores",
          periodo: "2024",
          descricao: "Manutenção preventiva e corretiva em desktops e notebooks. Formatação, instalação e configuração de sistemas operacionais, softwares e drivers. Diagnóstico e resolução de problemas de hardware e desempenho.",
        },
      ],
      educacoes: [
        {
          id: "ited1",
          instituicao: "Centro Universitário Luterano de Palmas - CEULP/ULBRA",
          curso: "Graduação em Engenharia de Software",
          periodo: "2025 - 2028 (Previsão)",
          descricao: "Foco em: Arquitetura de Software e Desenvolvimento Full Stack.",
        },
        {
          id: "ited2",
          instituicao: "Senai - Cetec Palmas",
          curso: "Curso Técnico em Informática",
          periodo: "2024 - 2025",
          descricao: "Destaque: Redes de computadores, suporte e lógica de programação.",
        },
        {
          id: "ited3",
          instituicao: "CEMT - Centro de Ensino Médio de Taquaralto",
          curso: "Ensino Médio Completo",
          periodo: "2022",
          descricao: "",
        },
      ],
      habilidades: [
        "Python, JavaScript, Node.js",
        "React, HTML5, CSS3, APIs, Web Responsivo",
        "SQL & Modelagem de Dados",
        "Git, GitHub, VS Code",
        "Suporte de Hardware & Redes",
        "Linux & Windows",
        "Raciocínio Lógico & Algoritmos",
        "Trabalho em Equipe e Resolução de Desafios",
        "Metodologias Ágeis",
        "Comunicação Técnica de Soluções",
      ],
      idiomas: [
        { id: "iti1", idioma: "Português", nivel: "Nativo" },
        { id: "iti2", idioma: "Inglês", nivel: "Técnico (Foco em leitura de documentação e termos de software)" },
        { id: "iti3", idioma: "Espanhol", nivel: "Básico/Intermediário" },
      ],
      certificacoes: [
        "Python – Santander Open Academy",
        "Introdução à Ciência de Dados – Santander Open Academy",
        "Introdução à IA Generativa – Santander Open Academy",
        "Prompting Responsável: Maximizar a IA no seu negócio – Santander Open Academy",
        "Storytelling para Marketing Digital – Santander Open Academy",
      ],
    },
  },
};
